#!/usr/bin/env python3
"""
DIGIPASS Digital Will PDF Generator
Generates professional 2-page Digital Will and Estate Declaration PDF
using ReportLab library
"""

import sys
import json
from datetime import datetime
from io import BytesIO
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT, TA_JUSTIFY

# ════════════════════════════════════════════════════════════════════════════════
# CUSTOM CANVAS CLASS FOR DYNAMIC PAGE COUNTING
# ════════════════════════════════════════════════════════════════════════════════

class PageCountCanvas(canvas.Canvas):
    """Canvas that supports total page count in footers."""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []
        self._testator_name = ""
        self._instrument_no = ""

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for idx, state in enumerate(self._saved_page_states, 1):
            self.__dict__.update(state)
            self._draw_page_footer_with_count(idx, num_pages)
            canvas.Canvas.showPage(self)
        canvas.Canvas.save(self)

    def _draw_page_footer_with_count(self, page_num, total_pages):
        W = self._pagesize[0]
        footer_h = 11 * mm
        sage = colors.HexColor('#8cbf9c')
        forest = colors.HexColor('#1b3a2d')
        ML = 20 * mm
        MR = W - 20 * mm

        # SAGE line above footer
        self.setStrokeColor(sage)
        self.setLineWidth(0.6)
        self.line(0, footer_h, W, footer_h)

        # FOREST footer band
        self.setFillColor(forest)
        self.rect(0, 0, W, footer_h, fill=1, stroke=0)

        # Footer text
        self.setFillColor(sage)
        self.setFont('Helvetica', 7)
        y_text = 4 * mm

        left_text = "Generated by DIGIPASS  ·  digipass.app"
        center_text = f"DIGITAL WILL AND ESTATE DECLARATION — {self._testator_name}"
        right_text = f"Instrument No. {self._instrument_no}  ·  Page {page_num} of {total_pages}"

        self.drawString(ML, y_text, left_text)
        self.drawCentredString(W / 2, y_text, center_text)
        self.drawRightString(MR, y_text, right_text)

# ════════════════════════════════════════════════════════════════════════════════
# COLOR & LAYOUT CONSTANTS
# ════════════════════════════════════════════════════════════════════════════════

COLORS = {
    'FOREST': colors.HexColor('#1b3a2d'),
    'FOREST_MID': colors.HexColor('#2d5a42'),
    'FOREST_LIGHT': colors.HexColor('#3d7a5a'),
    'SAGE': colors.HexColor('#8cbf9c'),
    'CREAM': colors.HexColor('#f5ead8'),
    'CREAM_LIGHT': colors.HexColor('#fdf6ec'),
    'SAND': colors.HexColor('#e8d9c0'),
    'SAND_DEEP': colors.HexColor('#d4c4a0'),
    'TEXT_DARK': colors.HexColor('#1a2e22'),
    'TEXT_BODY': colors.HexColor('#2c3a2e'),
    'TEXT_MID': colors.HexColor('#5a7260'),
    'TEXT_LIGHT': colors.HexColor('#8a9e90'),
    'WHITE': colors.HexColor('#ffffff'),
    'GREEN': colors.HexColor('#3d7a5a'),
    'AMBER': colors.HexColor('#7a5a00'),
    'RULE': colors.HexColor('#d4c4a0'),
    'RULE_DARK': colors.HexColor('#c4b090'),
}

PAGE_WIDTH, PAGE_HEIGHT = A4
ML = 20 * mm
MR = PAGE_WIDTH - 20 * mm
CW = MR - ML
TOP_MARGIN = 15 * mm

FOOTER_HEIGHT = 11 * mm
SAFE_BUFFER = 15 * mm
BOTTOM_LIMIT = FOOTER_HEIGHT + SAFE_BUFFER

SECTION_GAP = 8 * mm
RULE_GAP = 5 * mm
CARD_GAP = 2 * mm
PARA_LINE_HEIGHT = 5 * mm

ASSET_CARD_H = 16 * mm
EXECUTOR_CARD_H = 17 * mm
PREAMBLE_H = 32 * mm
DISCLAIMER_H = 28 * mm
SIG_BOX_H = 22 * mm
ARTICLE_HEAD_H = 8 * mm
CONTINUATION_HEADER_HEIGHT = 18 * mm

ACTION_DISPLAY = {
    'last_message':   'Deliver Final Message',
    'delete':         'Delete Account',
    'memorialise':    'Memorialise Account',
    'memorialize':    'Memorialise Account',
    'transfer':       'Transfer to Family',
    'download':       'Download & Archive Data',
    'deactivate':     'Deactivate Account',
    'pass_executor':  'Pass to Executor',
    'pass to executor': 'Pass to Executor',
    'no_action':      'No Action Required',
}

CATEGORY_COLORS = {
    'social':  ('#ddeaf5', '#1a4a6e'),
    'finance': ('#d4ead8', '#1b3a2d'),
    'storage': ('#f0e6d4', '#7a4f1a'),
    'email':   ('#ede8f5', '#4a3080'),
    'default': ('#e8d9c0', '#5a7260'),
}

# ════════════════════════════════════════════════════════════════════════════════
# UTILITY & FORMATTING FUNCTIONS
# ════════════════════════════════════════════════════════════════════════════════

def number_to_words(n):
    """Convert number to English words for year"""
    ones = ['', 'One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine']
    teens = ['Ten', 'Eleven', 'Twelve', 'Thirteen', 'Fourteen', 'Fifteen', 
             'Sixteen', 'Seventeen', 'Eighteen', 'Nineteen']
    tens = ['', '', 'Twenty', 'Thirty', 'Forty', 'Fifty', 'Sixty', 'Seventy', 'Eighty', 'Ninety']
    
    if n < 10:
        return ones[n]
    elif n < 20:
        return teens[n - 10]
    elif n < 100:
        return tens[n // 10] + ('' if n % 10 == 0 else ' ' + ones[n % 10])
    elif n < 1000:
        return ones[n // 100] + ' Hundred' + ('' if n % 100 == 0 else ' ' + number_to_words(n % 100))
    elif n < 1000000:
        return number_to_words(n // 1000) + ' Thousand' + ('' if n % 1000 == 0 else ' ' + number_to_words(n % 1000))
    return str(n)

def roman_numeral(n):
    """Convert integer to Roman numeral"""
    val = [1000, 900, 500, 400, 100, 90, 50, 40, 10, 9, 5, 4, 1]
    syms = ['M', 'CM', 'D', 'CD', 'C', 'XC', 'L', 'XL', 'X', 'IX', 'V', 'IV', 'I']
    roman_num = ''
    i = 0
    while n > 0:
        for _ in range(n // val[i]):
            roman_num += syms[i]
            n -= val[i]
        i += 1
    return roman_num

def format_action(raw):
    if not raw:
        return 'As per executor discretion'
    key = raw.lower().strip().replace(' ', '_')
    return ACTION_DISPLAY.get(key,
           ACTION_DISPLAY.get(raw.lower().strip(),
           raw.replace('_', ' ').title()))

def truncate(text, max_chars=55):
    if not text:
        return '—'
    return text[:max_chars] + '…' if len(text) > max_chars else text

# ════════════════════════════════════════════════════════════════════════════════
# DRAWING HELPERS
# ════════════════════════════════════════════════════════════════════════════════

def draw_vault_icon(c, x, y, size=28, on_dark=True):
    """Draw DIGIPASS vault icon"""
    stroke_color = COLORS['CREAM_LIGHT'] if on_dark else COLORS['FOREST']
    dot_color = COLORS['SAGE']
    bg_color = COLORS['FOREST_MID'] if on_dark else COLORS['SAND']

    # Rounded square background
    c.setFillColor(bg_color)
    c.roundRect(x, y - size, size, size, size * 0.2, fill=1, stroke=0)

    # Vault rectangle body
    vx = x + size * 0.23
    vy = y - size * 0.27
    vw = size * 0.54
    vh = size * 0.35
    c.setStrokeColor(stroke_color)
    c.setLineWidth(1.5)
    c.roundRect(vx, vy - vh, vw, vh, 3, fill=0, stroke=1)

    # Horizontal divider
    c.setLineWidth(1)
    c.line(vx, vy - vh * 0.45, vx + vw, vy - vh * 0.45)

    # Green squares inside vault
    c.setFillColor(dot_color)
    c.rect(vx + vw * 0.1, vy - vh * 0.9, vw * 0.25, vh * 0.35, fill=1, stroke=0)
    c.setFillAlpha(0.45)
    c.rect(vx + vw * 0.45, vy - vh * 0.9, vw * 0.25, vh * 0.35, fill=1, stroke=0)
    c.setFillAlpha(1)

    # Key pin
    kx = x + size * 0.65
    ky = y - size * 0.1
    c.setFillColor(stroke_color)
    c.circle(kx, ky, size * 0.07, fill=1, stroke=0)
    c.setStrokeColor(stroke_color)
    c.setLineWidth(1.5)
    c.line(kx, ky - size * 0.07, kx, vy)

def draw_page_background(c):
    c.setFillColor(COLORS['CREAM'])
    c.rect(0, 0, PAGE_WIDTH, PAGE_HEIGHT, fill=1, stroke=0)

def draw_page_border_rules(c):
    c.setFillColor(COLORS['FOREST'])
    c.rect(0, 0, 3.5 * mm, PAGE_HEIGHT, fill=1, stroke=0)
    c.rect(PAGE_WIDTH - 3.5 * mm, 0, 3.5 * mm, PAGE_HEIGHT, fill=1, stroke=0)

def draw_continuation_header(c, page_data):
    """Draw continuation header with explicit coordinates — NO shared functions"""
    W = PAGE_WIDTH
    H = PAGE_HEIGHT

    # 1. FOREST band — compact 18mm
    c.setFillColor(colors.HexColor('#1b3a2d'))
    c.rect(0, H - 18 * mm, W, 18 * mm, fill=1, stroke=0)

    # 2. SAGE accent line at bottom of band
    c.setStrokeColor(colors.HexColor('#8cbf9c'))
    c.setLineWidth(0.7)
    c.line(0, H - 18 * mm, W, H - 18 * mm)

    # 3. Left border rule (must redraw on new page)
    c.setFillColor(colors.HexColor('#1b3a2d'))
    c.rect(0, 0, 3.5 * mm, H, fill=1, stroke=0)

    # 4. Right border rule
    c.rect(W - 3.5 * mm, 0, 3.5 * mm, H, fill=1, stroke=0)

    # 5. Vault icon — small, inside band
    draw_vault_icon(c, 6 * mm, H - 3 * mm, size=16, on_dark=True)

    # 6. "Digipass" wordmark — inline, right of icon
    c.setFillColor(colors.HexColor('#fdf6ec'))
    c.setFont('Helvetica-Bold', 11)
    c.drawString(25 * mm, H - 8 * mm, 'Digipass')

    # 7. "DIGITAL ESTATE" tagline — SAME LINE as wordmark
    c.setFillColor(colors.HexColor('#8cbf9c'))
    c.setFont('Helvetica', 6.5)
    c.drawString(25 * mm, H - 13 * mm, 'DIGITAL  ESTATE')

    # 8. Right side: document title + page info
    name = page_data.get('testator_name', '').upper()
    instr = page_data.get('instrument_no', '')
    c.setFillColor(colors.HexColor('#8cbf9c'))
    c.setFont('Helvetica', 7)
    MR_local = W - 6 * mm
    c.drawRightString(MR_local, H - 8 * mm,
        f'DIGITAL WILL — {name} (continued)')
    c.drawRightString(MR_local, H - 13 * mm, instr)

def check_page_break(c, y, block_height, page_data):
    """Only break if the ENTIRE block won't fit. Don't break for small gaps."""
    if y - block_height < BOTTOM_LIMIT:
        c.showPage()
        page_data['page_num'] += 1

        # Draw background and borders on new page
        draw_page_background(c)
        draw_page_border_rules(c)

        # Continuation header (compact, 18mm)
        draw_continuation_header(c, page_data)
        y = PAGE_HEIGHT - 18 * mm - 6 * mm  # below continuation header
    return y

def draw_header_page1(c, user_data):
    """Draw header band for Page 1"""
    # Full-width FOREST background
    c.setFillColor(COLORS['FOREST'])
    c.rect(0, PAGE_HEIGHT - 56 * mm, PAGE_WIDTH, 56 * mm, fill=1, stroke=0)
    
    # Decorative circle top-right
    circle_radius = 46 * mm
    c.setFillColor(COLORS['FOREST_MID'])
    c.circle(PAGE_WIDTH, PAGE_HEIGHT, circle_radius, fill=1, stroke=0)
    
    c.setFillColor(COLORS['FOREST'])
    c.circle(PAGE_WIDTH, PAGE_HEIGHT, 26 * mm, fill=1, stroke=0)
    
    # SAGE accent line at bottom
    c.setStrokeColor(COLORS['SAGE'])
    c.setLineWidth(0.7)
    c.line(0, PAGE_HEIGHT - 56 * mm, PAGE_WIDTH, PAGE_HEIGHT - 56 * mm)
    
    # Vault icon
    draw_vault_icon(c, ML, PAGE_HEIGHT - 8 * mm, size=28, on_dark=True)
    
    # Wordmark and tagline
    c.setFont("Helvetica-Bold", 16)
    c.setFillColor(COLORS['CREAM_LIGHT'])
    c.drawString(ML + 36 * mm, PAGE_HEIGHT - 11 * mm, "Digipass")
    
    c.setFont("Helvetica", 7)
    c.setFillColor(COLORS['SAGE'])
    c.drawString(ML + 37 * mm, PAGE_HEIGHT - 15 * mm, "DIGITAL  ESTATE")
    
    # Thin rule
    c.setStrokeColor(COLORS['FOREST_LIGHT'])
    c.setLineWidth(0.4)
    c.line(ML + 36 * mm, PAGE_HEIGHT - 17 * mm, ML + 100 * mm, PAGE_HEIGHT - 17 * mm)
    
    # Main title
    c.setFont("Helvetica-Bold", 20)
    c.setFillColor(COLORS['WHITE'])
    c.drawString(ML, PAGE_HEIGHT - 28 * mm, "DIGITAL WILL & ESTATE DECLARATION")
    
    # Subtitle
    c.setFont("Helvetica-Bold", 9.5)
    c.setFillColor(COLORS['SAGE'])
    c.drawString(ML, PAGE_HEIGHT - 36 * mm, "A STRUCTURED RECORD OF DIGITAL ASSETS AND EXECUTOR ASSIGNMENTS")
    
    # Document meta right-aligned
    now = datetime.now()
    instrument_no = f"DW-{now.strftime('%Y%m%d')}-U{user_data['id']}"
    
    c.setFont("Helvetica", 7)
    c.drawString(MR - 100 * mm, PAGE_HEIGHT - 44 * mm, f"INSTRUMENT NO.  {instrument_no}")
    c.drawString(MR - 100 * mm, PAGE_HEIGHT - 49.5 * mm, f"GENERATED: {now.strftime('%d %B %Y')}  ·  CONFIDENTIAL")

def draw_header_page2(c, user_data):
    """Draw header band for Page 2"""
    # Full-width FOREST background (shorter)
    c.setFillColor(COLORS['FOREST'])
    c.rect(0, PAGE_HEIGHT - 38 * mm, PAGE_WIDTH, 38 * mm, fill=1, stroke=0)
    
    # SAGE accent line
    c.setStrokeColor(COLORS['SAGE'])
    c.setLineWidth(0.7)
    c.line(0, PAGE_HEIGHT - 38 * mm, PAGE_WIDTH, PAGE_HEIGHT - 38 * mm)
    
    # Vault icon and wordmark
    draw_vault_icon(c, ML, PAGE_HEIGHT - 8 * mm, size=28, on_dark=True)
    
    c.setFont("Helvetica-Bold", 16)
    c.setFillColor(COLORS['CREAM_LIGHT'])
    c.drawString(ML + 36 * mm, PAGE_HEIGHT - 11 * mm, "Digipass")
    
    c.setFont("Helvetica", 7)
    c.setFillColor(COLORS['SAGE'])
    c.drawString(ML + 37 * mm, PAGE_HEIGHT - 15 * mm, "DIGITAL  ESTATE")
    
    # Page 2 title
    c.setFont("Helvetica-Bold", 16)
    c.setFillColor(COLORS['WHITE'])
    c.drawString(ML, PAGE_HEIGHT - 26 * mm, "SIGNATURE AND EXECUTION PAGE")
    
    # Right-aligned meta
    now = datetime.now()
    instrument_no = f"DW-{now.strftime('%Y%m%d')}-U{user_data['id']}"
    
    c.setFont("Helvetica", 7)
    c.setFillColor(COLORS['SAGE'])
    c.drawRightString(MR, PAGE_HEIGHT - 26 * mm, f"Instrument No. {instrument_no}")
    c.drawRightString(MR, PAGE_HEIGHT - 31 * mm, f"Digital Will and Estate Declaration of {user_data['full_name'].upper()}")

def draw_footer(c, page_data):
    """Footer is now handled by PageCountCanvas.save() method"""
    pass

def draw_preamble(c, y, user_data):
    """Draw preamble box"""
    box_height = PREAMBLE_H
    box_y = y - box_height
    
    # Drop shadow
    c.setFillColor(colors.HexColor('#d4c4a0'))
    c.roundRect(ML + 0.6 * mm, box_y - 0.6 * mm, CW, box_height, 2, fill=1, stroke=0)
    
    # Main card
    c.setFillColor(COLORS['CREAM_LIGHT'])
    c.setStrokeColor(COLORS['SAND_DEEP'])
    c.setLineWidth(0.5)
    c.roundRect(ML, box_y, CW, box_height, 2, fill=1, stroke=1)
    
    # Left strip
    c.setFillColor(COLORS['FOREST'])
    c.rect(ML, box_y, 5 * mm, box_height, fill=1, stroke=0)
    
    # Preamble text
    preamble_text = (
        f"KNOW ALL PERSONS BY THESE PRESENTS: I, {user_data['full_name'].upper()}, "
        f"User Identification Number #{user_data['id']}, registered with DIGIPASS Digital Estate Platform, "
        f"being of sound mind and memory, and not acting under duress, menace, fraud, or undue influence "
        f"of any person whatsoever, do hereby make, publish, and declare this my Digital Will and Estate Declaration, "
        f"hereby revoking all former digital wills and testamentary dispositions of digital property heretofore "
        f"made by me in this platform."
    )
    
    style = ParagraphStyle(
        name='Preamble',
        fontName='Helvetica',
        fontSize=8.5,
        textColor=COLORS['TEXT_MID'],
        leading=PARA_LINE_HEIGHT,
        alignment=TA_JUSTIFY,
    )
    p = Paragraph(preamble_text, style)
    p_w, p_h = p.wrapOn(c, CW - 12 * mm, box_height)
    p.drawOn(c, ML + 8 * mm, box_y + (box_height - p_h) / 2)
    
    return y - box_height - SECTION_GAP

def draw_article_heading(c, y, article_label, title_text):
    """Draw article heading with label, dot, and title"""
    # Article label
    c.setFont("Helvetica-Bold", 7)
    c.setFillColor(COLORS['FOREST'])
    c.drawString(ML, y, article_label)
    
    # SAGE dot
    c.setFillColor(COLORS['SAGE'])
    label_width = c.stringWidth(article_label, "Helvetica-Bold", 7)
    c.circle(ML + label_width + 3 * mm, y + 1 * mm, 1.1 * mm, fill=1, stroke=0)
    
    # Title
    c.setFont("Helvetica-Bold", 10.5)
    c.setFillColor(COLORS['FOREST'])
    c.drawString(ML + label_width + 8 * mm, y, title_text)
    
    # Rule below
    c.setStrokeColor(COLORS['SAND_DEEP'])
    c.setLineWidth(0.5)
    c.line(ML, y - 2.5 * mm, MR, y - 2.5 * mm)
    
    return y - ARTICLE_HEAD_H

def draw_signature_box(c, x, y, width, label, prefill=""):
    """Draw signature box component"""
    box_height = SIG_BOX_H
    
    # Main card
    c.setFillColor(COLORS['CREAM_LIGHT'])
    c.setStrokeColor(COLORS['SAND_DEEP'])
    c.setLineWidth(0.4)
    c.roundRect(x, y - box_height, width, box_height, 1.5, fill=1, stroke=1)
    
    # Top band
    c.setFillColor(COLORS['SAND'])
    c.rect(x, y - 7 * mm, width, 7 * mm, fill=1, stroke=0)
    c.roundRect(x, y - 7 * mm, width, 7 * mm, 1.5, fill=0, stroke=1) # border
    
    # Label in band
    c.setFont("Helvetica", 6.5)
    c.setFillColor(COLORS['FOREST'])
    c.drawString(x + 3 * mm, y - 4.5 * mm, label.upper())
    
    # Signature line
    c.setStrokeColor(COLORS['FOREST_LIGHT'])
    c.setLineWidth(0.6)
    c.line(x + 4 * mm, y - 16 * mm, x + width - 4 * mm, y - 16 * mm)
    
    # Prefill or X mark
    if prefill:
        c.setFont("Helvetica", 8.5)
        c.setFillColor(COLORS['TEXT_MID'])
        c.drawString(x + 4 * mm, y - 14 * mm, prefill)
    else:
        c.setFont("Helvetica", 12)
        c.setFillColor(COLORS['TEXT_LIGHT'])
        c.drawString(x + 4 * mm, y - 15.5 * mm, "✕")

def draw_rule_dark(c, y):
    c.setStrokeColor(COLORS['RULE_DARK'])
    c.setLineWidth(0.5)
    c.line(ML, y, MR, y)
    return y - 0.5

def draw_label(c, text, y):
    c.setFont("Helvetica-Bold", 9)
    c.setFillColor(COLORS['FOREST'])
    c.drawString(ML, y, text.upper())
    return y

def draw_multiline_text(c, text, x, y, max_width, style):
    p = Paragraph(text, style)
    p_w, p_h = p.wrapOn(c, max_width, PAGE_HEIGHT)
    p.drawOn(c, x, y - p_h)
    return p_h

def draw_left_right_borders(c):
    c.setFillColor(COLORS['FOREST'])
    c.rect(0, 0, 3.5 * mm, PAGE_HEIGHT, fill=1, stroke=0)
    c.rect(PAGE_WIDTH - 3.5 * mm, 0, 3.5 * mm, PAGE_HEIGHT, fill=1, stroke=0)

def draw_section_rule(c, y):
    """Two-tone rule with accent dot"""
    c.setStrokeColor(COLORS['SAND_DEEP'])
    c.setLineWidth(0.5)
    c.line(ML, y, MR, y)
    # Accent dot in center
    c.setFillColor(COLORS['SAGE'])
    c.circle(ML + (MR - ML) / 2, y, 0.8 * mm, fill=1, stroke=0)
    return y - 2 * mm

def draw_italic_paragraph(c, x, y, width, text, font_size=8, leading=12, color='#5a7260'):
    """Draw paragraph with italic formatting"""
    style = ParagraphStyle(
        name='ItalicPara',
        fontName='Helvetica-Oblique',
        fontSize=font_size,
        textColor=colors.HexColor(color),
        leading=leading,
        alignment=TA_JUSTIFY,
    )
    return draw_multiline_text(c, text, x, y, width, style)

def draw_article_heading_safe(c, y, label, title, page_data, min_content_below=None):
    """Don't draw heading unless there's room for heading + min content."""
    if min_content_below is None:
        min_content_below = 25 * mm
    heading_h = 8 * mm
    total_needed = heading_h + min_content_below
    
    y = check_page_break(c, y, total_needed, page_data)
    y = draw_article_heading(c, y, label, title)
    return y

# ════════════════════════════════════════════════════════════════════════════════
# PAGE 1 CONTENT
# ════════════════════════════════════════════════════════════════════════════════

def draw_page1(c, data, page_data):
    """Generate Page 1 content"""
    user_data = data['user']
    assets = data['assets']
    executors = data['executors']
    
    draw_header_page1(c, user_data)
    
    y = PAGE_HEIGHT - 64 * mm
    
    # Preamble
    y = check_page_break(c, y, PREAMBLE_H, page_data)
    y = draw_preamble(c, y, user_data)
    
    # Article I - Testator Identification
    y = check_page_break(c, y, ARTICLE_HEAD_H + 31 * mm, page_data)
    y = draw_article_heading(c, y, "ARTICLE  I", "TESTATOR IDENTIFICATION")
    y -= SECTION_GAP
    
    # Two-column field grid
    col_width = (CW - 5 * mm) / 2
    field_height = 13 * mm
    
    created_at_str = user_data.get('created_at', datetime.now().strftime('%Y-%m-%d'))
    try:
        created_date = datetime.fromisoformat(created_at_str.replace('Z', '+00:00'))
        date_display = created_date.strftime('%B %d, %Y')
    except (ValueError, TypeError):
        date_display = created_at_str

    fields = [
        [("FULL LEGAL NAME", user_data['full_name'].upper()),
         ("DATE OF REGISTRATION", date_display)],
        [("EMAIL ADDRESS", user_data['email']),
         ("DIGIPASS USER ID", f"DIGIPASS ID #{user_data['id']}")]
    ]
    
    for row in fields:
        for col_idx, (label, value) in enumerate(row):
            x = ML + col_idx * (col_width + 5 * mm)
            
            c.setFont("Helvetica", 6.5)
            c.setFillColor(COLORS['TEXT_LIGHT'])
            c.drawString(x, y - 3 * mm, label)
            
            c.setFont("Helvetica-Bold", 10)
            c.setFillColor(COLORS['TEXT_DARK'])
            c.drawString(x, y - 8.5 * mm, truncate(value, 40))
            
            c.setStrokeColor(COLORS['SAND_DEEP'])
            c.setLineWidth(0.5)
            c.line(x, y - 10.5 * mm, x + col_width - 5 * mm, y - 10.5 * mm)
        
        y -= field_height
    
    y -= RULE_GAP
    draw_rule_dark(c, y)
    y -= SECTION_GAP
    
    # Article II - Schedule of Digital Assets
    y = check_page_break(c, y, ARTICLE_HEAD_H, page_data)
    y = draw_article_heading(c, y, "ARTICLE  II", "SCHEDULE OF DIGITAL ASSETS")
    y -= SECTION_GAP
    
    intro_text = (
        "I give, bequeath, and assign the following digital assets, being the whole of my electronic "
        "estate as recorded within the DIGIPASS platform, to the designated Executor(s) in accordance "
        "with the permissions and instructions granted under Article III. Each asset shall be managed "
        "according to the preferred action specified herein:"
    )
    style = ParagraphStyle(name='Intro', fontName='Helvetica-Oblique', fontSize=8, textColor=COLORS['TEXT_MID'], leading=12)
    
    y = check_page_break(c, y, 40, page_data) # Approx height
    text_h = draw_multiline_text(c, intro_text, ML, y, CW, style)
    y -= text_h + SECTION_GAP
    
    # Asset cards
    for idx, asset in enumerate(assets, 1):
        y = check_page_break(c, y, ASSET_CARD_H + CARD_GAP, page_data)
        y = draw_asset_card(c, ML, y, CW, roman_numeral(idx), asset)
    
    y -= RULE_GAP
    draw_rule_dark(c, y)
    y -= SECTION_GAP
    
    # Article III - Appointment of Executors
    y = check_page_break(c, y, ARTICLE_HEAD_H, page_data)
    y = draw_article_heading(c, y, "ARTICLE  III", "APPOINTMENT OF EXECUTORS")
    y -= SECTION_GAP
    
    intro_text_exec = (
        "I hereby nominate, constitute, and appoint the following named individuals as Personal Executors "
        "of my digital estate within the DIGIPASS platform. Each Executor shall serve in a fiduciary capacity "
        "and shall have only such authority as is expressly granted herein. Sensitive credentials remain encrypted "
        "and are accessible solely through the secure DIGIPASS Executor Portal:"
    )
    
    y = check_page_break(c, y, 45, page_data) # Approx height
    text_h = draw_multiline_text(c, intro_text_exec, ML, y, CW, style)
    y -= text_h + SECTION_GAP
    
    # Executor cards
    romans = ['I','II','III','IV','V','VI','VII','VIII','IX','X']
    for i, executor in enumerate(data.get('executors', [])):
        roman = romans[i] if i < len(romans) else str(i+1)
        y = check_page_break(c, y, EXECUTOR_CARD_H + CARD_GAP, page_data)
        y = draw_executor_card(c, ML, y, CW, roman, executor)

    y -= 5 * mm
    draw_rule_dark(c, y)
    y -= SECTION_GAP

    # ── ARTICLE IV: FINAL MESSAGES ──
    y = draw_article_heading_safe(c, y, "ARTICLE  IV",
        "EXECUTOR INSTRUCTIONS & FINAL MESSAGES", page_data,
        min_content_below=20 * mm)
    y -= SECTION_GAP

    # Intro paragraph
    intro = ("The following instructions and final messages have been "
             "left by the Testator for each designated asset. These "
             "instructions are to be carried out faithfully and in "
             "accordance with the Testator's expressed wishes:")
    y = draw_italic_paragraph(c, ML, y, CW, intro, font_size=8, leading=12, color='#5a7260')
    y -= 6 * mm

    # Final message cards — one per asset
    for asset in data.get('assets', []):
        msg = (asset.get('final_message') or
               'No final message left.').strip()
        card_h = 20 * mm
        y = check_page_break(c, y, card_h + 3 * mm, page_data)

        # Shadow
        c.setFillColor(colors.HexColor('#d4c4a0'))
        c.roundRect(ML + 0.6 * mm, y - card_h - 0.6 * mm,
                    CW, card_h, 2 * mm, fill=1, stroke=0)

        # Card
        c.setFillColor(colors.HexColor('#fdf6ec'))
        c.setStrokeColor(colors.HexColor('#d4c4a0'))
        c.setLineWidth(0.4)
        c.roundRect(ML, y - card_h, CW, card_h,
                    2 * mm, fill=1, stroke=1)

        # SAGE left strip
        c.setFillColor(colors.HexColor('#8cbf9c'))
        c.roundRect(ML, y - card_h, 5 * mm, card_h,
                    2 * mm, fill=1, stroke=0)
        c.rect(ML + 3 * mm, y - card_h, 2 * mm, card_h,
               fill=1, stroke=0)

        # Asset name
        c.setFillColor(colors.HexColor('#1a2e22'))
        c.setFont('Helvetica-Bold', 9.5)
        c.drawString(ML + 8 * mm, y - 6 * mm,
                     asset.get('name', '').upper())

        # Category badge
        cat = asset.get('category', '').lower()
        CAT_COLORS = {
            'social':  ('#ddeaf5', '#1a4a6e'),
            'finance': ('#d4ead8', '#1b3a2d'),
            'storage': ('#f0e6d4', '#7a4f1a'),
            'email':   ('#ede8f5', '#4a3080'),
        }
        badge_bg, badge_fg = CAT_COLORS.get(cat, ('#e8d9c0', '#5a7260'))
        badge_text = cat.upper() if cat else 'OTHER'
        badge_w = 18 * mm
        # Estimate name width to place badge after it
        name_w = len(asset.get('name','')) * 2 * mm
        bx = ML + 8 * mm + name_w + 3 * mm
        c.setFillColor(colors.HexColor(badge_bg))
        c.roundRect(bx, y - 7.5 * mm, badge_w, 4.2 * mm,
                    1.2 * mm, fill=1, stroke=0)
        c.setFillColor(colors.HexColor(badge_fg))
        c.setFont('Helvetica', 6.5)
        c.drawString(bx + 2.5 * mm, y - 5.8 * mm, badge_text)

        # "Final Message" label
        c.setFillColor(colors.HexColor('#8a9e90'))
        c.setFont('Helvetica', 7)
        c.drawString(ML + 8 * mm, y - 11 * mm, 'FINAL MESSAGE')

        # Message text
        display_msg = msg[:90] + '…' if len(msg) > 90 else msg
        c.setFillColor(colors.HexColor('#5a7260'))
        c.setFont('Helvetica-Oblique', 8.5)
        c.drawString(ML + 8 * mm, y - 15.5 * mm, f'"{display_msg}"')

        y -= card_h + 3 * mm

    y -= 5 * mm
    draw_rule_dark(c, y)
    y -= SECTION_GAP

    # ── ARTICLE V: DISCLAIMER ──
    y = draw_article_heading_safe(c, y, "ARTICLE  V",
        "GOVERNING TERMS AND LEGAL DISCLAIMER", page_data,
        min_content_below=28 * mm)
    y -= SECTION_GAP

    disclaimer_text = (
        "This instrument has been generated by DIGIPASS, a digital estate "
        "management platform, and constitutes a formal structured record of "
        "the Testator's digital estate. This document is intended to "
        "supplement — and not replace — a legally executed will under the "
        "laws of the applicable jurisdiction. The Testator is strongly "
        "advised to seek independent legal counsel to give this instrument "
        "full binding legal effect. Sensitive asset credentials are "
        "encrypted and intentionally excluded from this printed will; they "
        "remain accessible solely through the secure DIGIPASS Executor "
        "Portal. DIGIPASS accepts no liability for the legal validity of "
        "this instrument in any jurisdiction."
    )

    # Disclaimer card with SAGE left strip
    card_h = 30 * mm
    y = check_page_break(c, y, card_h + 2 * mm, page_data)
    c.setFillColor(colors.HexColor('#fdf6ec'))
    c.setStrokeColor(colors.HexColor('#d4c4a0'))
    c.setLineWidth(0.4)
    c.roundRect(ML, y - card_h, CW, card_h, 2 * mm, fill=1, stroke=1)
    c.setFillColor(colors.HexColor('#8cbf9c'))
    c.roundRect(ML, y - card_h, 5 * mm, card_h, 2 * mm, fill=1, stroke=0)
    c.rect(ML + 3 * mm, y - card_h, 2 * mm, card_h, fill=1, stroke=0)

    # Draw disclaimer text inside card
    style_disc = ParagraphStyle('disc',
        fontName='Helvetica', fontSize=7.8,
        textColor=colors.HexColor('#5a7260'),
        leading=12, alignment=TA_JUSTIFY,
        leftIndent=0, rightIndent=0)
    p = Paragraph(disclaimer_text, style_disc)
    p.wrapOn(c, CW - 12 * mm, card_h - 6 * mm)
    p.drawOn(c, ML + 8 * mm, y - card_h + 3 * mm)
    
    # ── END OF CONTENT PAGES ──
    c.showPage()
    page_data['page_num'] += 1

    # ── SIGNATURE PAGE ──
    draw_page_background(c)
    draw_left_right_borders(c)
    draw_signature_page(c, data, page_data)

def draw_asset_card(c, x, y, width, roman, asset):
    card_height = ASSET_CARD_H
    shadow_offset = 0.6 * mm

    c.setFillColor(COLORS['SAND_DEEP'])
    c.roundRect(x + shadow_offset, y - card_height - shadow_offset, width, card_height, 2, fill=1, stroke=0)
    
    c.setFillColor(COLORS['CREAM_LIGHT'])
    c.setStrokeColor(COLORS['SAND_DEEP'])
    c.setLineWidth(0.4)
    c.roundRect(x, y - card_height, width, card_height, 2, fill=1, stroke=1)
    
    strip_w = 6 * mm
    c.setFillColor(COLORS['FOREST'])
    c.roundRect(x, y - card_height, strip_w, card_height, 2, fill=1, stroke=0)
    c.rect(x + strip_w - 2*mm, y - card_height, 2*mm, card_height, fill=1, stroke=0)

    c.setFont("Helvetica-Bold", 7)
    c.setFillColor(COLORS['WHITE'])
    c.drawCentredString(x + strip_w/2, y - card_height/2 - 1.5*mm, roman)
    
    c.setFont("Helvetica-Bold", 10)
    c.setFillColor(COLORS['TEXT_DARK'])
    c.drawString(x + 9 * mm, y - 5.5 * mm, truncate(asset['name'].upper(), 30))
    
    badge_colors = {
        'social': (colors.HexColor('#ddeaf5'), colors.HexColor('#1a4a6e')),
        'finance': (colors.HexColor('#d4ead8'), colors.HexColor('#1b3a2d')),
        'storage': (colors.HexColor('#f0e6d4'), colors.HexColor('#7a4f1a')),
        'email': (colors.HexColor('#ede8f5'), colors.HexColor('#4a3080')),
        'default': (COLORS['SAND'], COLORS['TEXT_MID'])
    }
    bg_color, text_color = badge_colors.get(asset.get('category', 'default'), badge_colors['default'])
    
    c.setFillColor(bg_color)
    c.roundRect(x + 100 * mm, y - 7.5 * mm, 25 * mm, 4.2 * mm, 1.2, fill=1, stroke=0)
    
    c.setFont("Helvetica", 6.5)
    c.setFillColor(text_color)
    c.drawCentredString(x + 112.5 * mm, y - 5.5 * mm, asset.get('category', 'ASSET').upper())
    
    c.setFont("Helvetica", 8)
    c.setFillColor(COLORS['TEXT_MID'])
    c.drawString(x + 9 * mm, y - 11 * mm, truncate(asset.get('description', ''), 55))
    
    c.setFont("Helvetica", 7)
    c.setFillColor(COLORS['TEXT_LIGHT'])
    action = format_action(asset.get('preferred_action'))
    c.drawRightString(MR - 2 * mm, y - 5.5 * mm, f"Preferred Action: {action}")
    
    created_at_str = asset.get('created_at', '')
    try:
        created_date = datetime.fromisoformat(created_at_str.replace('Z', '+00:00'))
        date_display = created_date.strftime('%B %d, %Y')
    except (ValueError, TypeError):
        date_display = created_at_str
    c.drawRightString(MR - 2 * mm, y - 11 * mm, f"Added: {date_display}")
    
    return y - card_height - CARD_GAP

def draw_executor_card(c, x, y, width, roman, executor):
    """
    executor dict keys: name, email, relationship,
                        status, access_granted, created_at
    """
    card_height = EXECUTOR_CARD_H
    shadow_offset = 0.6 * mm

    # Drop shadow
    c.setFillColor(colors.HexColor('#d4c4a0'))
    c.roundRect(x + shadow_offset, y - card_height - shadow_offset,
                width, card_height, 2*mm, fill=1, stroke=0)

    # Card background
    c.setFillColor(colors.HexColor('#fdf6ec'))
    c.setStrokeColor(colors.HexColor('#d4c4a0'))
    c.setLineWidth(0.4)
    c.roundRect(x, y - card_height, width, card_height, 2*mm, fill=1, stroke=1)

    # Left strip — FOREST_LIGHT for executors
    strip_w = 6 * mm
    c.setFillColor(colors.HexColor('#3d7a5a'))
    c.roundRect(x, y - card_height, strip_w, card_height, 2*mm, fill=1, stroke=0)
    # Patch right edge of strip (remove double-radius on right)
    c.rect(x + strip_w - 2*mm, y - card_height, 2*mm, card_height, fill=1, stroke=0)

    # Roman numeral in strip
    c.setFillColor(colors.white)
    c.setFont('Helvetica-Bold', 7)
    c.drawCentredString(x + strip_w/2, y - card_height/2 - 1.5*mm, roman)

    # Name
    name = truncate(executor.get('name', '').upper(), 30)
    c.setFillColor(colors.HexColor('#1a2e22'))
    c.setFont('Helvetica-Bold', 10)
    c.drawString(x + 9 * mm, y - 5.5 * mm, name)

    # Email
    c.setFillColor(colors.HexColor('#5a7260'))
    c.setFont('Helvetica', 8)
    c.drawString(x + 9 * mm, y - 10.5 * mm,
                 truncate(executor.get('email', ''), 40))

    # Appointed date
    c.setFillColor(colors.HexColor('#8a9e90'))
    c.setFont('Helvetica', 7)
    date_str = executor.get('created_at', '')
    try:
        created_date = datetime.fromisoformat(date_str.replace('Z', '+00:00'))
        date_display = created_date.strftime('%B %d, %Y')
    except (ValueError, TypeError):
        date_display = date_str
    c.drawString(x + 9 * mm, y - 14.5 * mm, f"Appointed: {date_display}")

    # Right-side three columns
    col_positions = [
        (width - 72 * mm, 'RELATIONSHIP', executor.get('relationship', '—')),
        (width - 44 * mm, 'STATUS',       executor.get('status', '—').capitalize()),
        (width - 16 * mm, 'ACCESS',
         'Granted' if executor.get('access_granted') else 'Pending'),
    ]
    for col_x_offset, label, value in col_positions:
        col_x = x + col_x_offset
        # Label
        c.setFillColor(colors.HexColor('#8a9e90'))
        c.setFont('Helvetica', 6.5)
        c.drawRightString(col_x, y - 4.5 * mm, label)
        # Value
        if label == 'STATUS':
            val_color = '#3d7a5a' if value.lower() == 'verified' else '#1b3a2d'
        elif label == 'ACCESS':
            val_color = '#3d7a5a' if value == 'Granted' else '#7a5a00'
        else:
            val_color = '#2c3a2e'
        c.setFillColor(colors.HexColor(val_color))
        c.setFont('Helvetica-Bold', 8.5)
        c.drawRightString(col_x, y - 9.5 * mm, value)

    return y - card_height - CARD_GAP

# ════════════════════════════════════════════════════════════════════════════════
# PAGE 2 CONTENT
# ════════════════════════════════════════════════════════════════════════════════

def draw_signature_page(c, data, page_data):
    """Draw the complete signature and execution page"""
    W = PAGE_WIDTH
    H = PAGE_HEIGHT
    ML_val = 20 * mm
    MR_val = W - 20 * mm
    CW_val = MR_val - ML_val

    name = data['user'].get('full_name', '').upper()
    date_str = data.get('generated_date',
               datetime.now().strftime('%B %d, %Y'))
    day = str(datetime.now().day)
    month = datetime.now().strftime('%B')
    year_text = 'Two Thousand Twenty Six'
    instr = page_data.get('instrument_no', '')

    y = H

    # ── 1. HEADER BAND (38mm) ──
    c.setFillColor(colors.HexColor('#1b3a2d'))
    c.rect(0, H - 38 * mm, W, 38 * mm, fill=1, stroke=0)

    # Decorative circle (smaller than page 1)
    c.setFillColor(colors.HexColor('#2d5a42'))
    c.circle(W, H, 34 * mm, fill=1, stroke=0)
    c.setFillColor(colors.HexColor('#1b3a2d'))
    c.circle(W, H, 18 * mm, fill=1, stroke=0)

    # SAGE accent line
    c.setStrokeColor(colors.HexColor('#8cbf9c'))
    c.setLineWidth(0.7)
    c.line(0, H - 38 * mm, W, H - 38 * mm)

    # Vault icon + wordmark
    draw_vault_icon(c, ML_val, H - 8 * mm, size=26, on_dark=True)
    c.setFillColor(colors.HexColor('#fdf6ec'))
    c.setFont('Helvetica-Bold', 15)
    c.drawString(ML_val + 32 * mm, H - 14 * mm, 'Digipass')
    c.setFillColor(colors.HexColor('#8cbf9c'))
    c.setFont('Helvetica', 7)
    c.drawString(ML_val + 33 * mm, H - 19 * mm,
                 'DIGITAL  ESTATE')

    # Title
    c.setFillColor(colors.HexColor('#ffffff'))
    c.setFont('Helvetica-Bold', 16)
    c.drawString(ML_val, H - 27 * mm,
                 'SIGNATURE AND EXECUTION PAGE')

    # Right meta
    c.setFillColor(colors.HexColor('#8cbf9c'))
    c.setFont('Helvetica', 7)
    c.drawRightString(MR_val, H - 27 * mm, f'Instrument No. {instr}')
    c.drawRightString(MR_val, H - 32 * mm,
        f'Digital Will and Estate Declaration of {name}')

    y = H - 38 * mm - 8 * mm

    # ── 2. EXECUTION STATEMENT ──
    exec_text = (
        f"IN WITNESS WHEREOF, I, <b>{name}</b>, the Testator named in "
        f"this Digital Will and Estate Declaration, have hereunto set my "
        f"hand and seal to this instrument, on this {day} day of {month}, "
        f"in the year <b>{year_text}</b>, declaring and publishing this as "
        f"my Digital Will and Estate Declaration of digital assets."
    )
    exec_style = ParagraphStyle('exec',
        fontName='Helvetica', fontSize=9,
        textColor=colors.HexColor('#2c3a2e'),
        leading=15, alignment=TA_JUSTIFY)
    ep = Paragraph(exec_text, exec_style)
    ep_w, ep_h = ep.wrapOn(c, CW_val, 50 * mm)
    ep.drawOn(c, ML_val, y - ep_h)
    y -= ep_h + 8 * mm

    # ── 3. RULE DARK ──
    c.setStrokeColor(colors.HexColor('#c4b090'))
    c.setLineWidth(0.5)
    c.line(ML_val, y, MR_val, y)
    y -= 8 * mm

    # ── 4. TESTATOR SECTION ──
    c.setFillColor(colors.HexColor('#1b3a2d'))
    c.setFont('Helvetica-Bold', 9)
    c.drawString(ML_val, y, 'TESTATOR')
    y -= 7 * mm

    for line in [
        f"I, {name}, sign my name to this instrument this {date_str},",
        "and being first duly sworn, declare to the undersigned authority",
        "that I sign and execute this instrument as my Digital Will willingly.",
    ]:
        c.setFillColor(colors.HexColor('#5a7260'))
        c.setFont('Helvetica', 8.5)
        c.drawString(ML_val, y, line)
        y -= 5 * mm
    y -= 4 * mm

    # ── 5. TWO SIG BOXES ──
    draw_signature_box(c, ML_val, y, 80 * mm,
                 'SIGNATURE OF TESTATOR',
                 data['user'].get('full_name', ''))
    draw_signature_box(c, ML_val + 90 * mm, y, 80 * mm,
                 'DATE', date_str)
    y -= 22 * mm + 10 * mm

    # ── 6. RULE DARK ──
    c.setStrokeColor(colors.HexColor('#c4b090'))
    c.setLineWidth(0.5)
    c.line(ML_val, y, MR_val, y)
    y -= 8 * mm

    # ── 7. NOTARIAL ACKNOWLEDGEMENT ──
    c.setFillColor(colors.HexColor('#1b3a2d'))
    c.setFont('Helvetica-Bold', 9)
    c.drawString(ML_val, y,
        'NOTARIAL ACKNOWLEDGEMENT  /  OFFICIAL SEAL')
    y -= 8 * mm

    notary_text = (
        "State / Jurisdiction of ____________________    "
        "Country / District of ____________________<br/><br/>"
        f"Subscribed, sworn to and acknowledged before me by "
        f"<b>{name}</b>, the Testator, this ______ day of "
        "____________________, 20____."
    )
    notary_style = ParagraphStyle('notary',
        fontName='Helvetica', fontSize=8.5,
        textColor=colors.HexColor('#5a7260'),
        leading=14)
    np = Paragraph(notary_text, notary_style)
    np_w, np_h = np.wrapOn(c, CW_val - 52 * mm, 40 * mm)
    np.drawOn(c, ML_val, y - np_h)

    # ── 8. NOTARY SEAL (right of paragraph) ──
    seal_cx = MR_val - 22 * mm
    seal_cy = y - 18 * mm
    draw_notary_seal(c, seal_cx, seal_cy)

    y -= max(np_h, 36 * mm) + 10 * mm

    # ── 9. NOTARY SIG BOX ──
    draw_signature_box(c, ML_val, y, 100 * mm,
        'NOTARY PUBLIC — SIGNATURE & COMMISSION NO.', '')
    y -= 22 * mm + 10 * mm

    # ── 10. RULE DARK ──
    c.setStrokeColor(colors.HexColor('#c4b090'))
    c.setLineWidth(0.5)
    c.line(ML_val, y, MR_val, y)
    y -= 8 * mm

    # ── 11. CERTIFICATION LINE ──
    c.setFillColor(colors.HexColor('#8a9e90'))
    c.setFont('Helvetica', 7.5)
    cert = (f"This document was digitally generated by DIGIPASS  ·  "
            f"digipass.app  ·  Instrument No. {instr}  ·  {date_str}")
    c.drawCentredString(W / 2, y, cert)
    # Footer is handled by PageCountCanvas automatically
    
    # Finalize the signature page
    c.showPage()

def draw_notary_seal(c, cx, cy):
    """Draw notary seal with text inside circle"""
    outer_r = 18 * mm
    inner_r = 15 * mm

    # Outer circle
    c.setFillColor(colors.HexColor('#fdf6ec'))
    c.setStrokeColor(colors.HexColor('#3d7a5a'))
    c.setLineWidth(0.8)
    c.circle(cx, cy, outer_r, fill=1, stroke=1)

    # Inner circle
    c.setFillColor(colors.HexColor('#fdf6ec'))
    c.setStrokeColor(colors.HexColor('#8cbf9c'))
    c.setLineWidth(0.4)
    c.circle(cx, cy, inner_r, fill=1, stroke=1)

    # Vault icon — centered inside seal
    icon_size = 14 * mm
    draw_vault_icon(c, cx - icon_size / 2, cy + icon_size / 2 + 2 * mm, size=icon_size, on_dark=False)

    # Text lines INSIDE circle, below icon
    c.setFillColor(colors.HexColor('#1b3a2d'))
    c.setFont('Helvetica-Bold', 5.5)
    c.drawCentredString(cx, cy - 4 * mm,  'DIGIPASS')
    c.drawCentredString(cx, cy - 7 * mm,  'DIGITAL ESTATE')
    c.drawCentredString(cx, cy - 10 * mm, 'OFFICIAL SEAL')

# ════════════════════════════════════════════════════════════════════════════════
# MAIN GENERATION FUNCTION
# ════════════════════════════════════════════════════════════════════════════════

def generate_pdf(data):
    """Main function to generate the complete multi-page PDF"""
    output = BytesIO()
    
    c = PageCountCanvas(output, pagesize=A4)
    c.setTitle(f"Digital Will and Estate Declaration — {data['user']['full_name']}")
    c.setAuthor("DIGIPASS")
    c.setSubject("Digital Will and Estate Declaration of Digital Assets")
    c.setKeywords("digital will, digipass, digital estate, digital inheritance, testament")
    
    # Set testator info for PageCountCanvas footer rendering
    now = datetime.now()
    c._testator_name = data['user']['full_name'].upper()
    c._instrument_no = f"DW-{now.strftime('%Y%m%d')}-U{data['user']['id']}"
    
    page_data = {
        'page_num': 1,
        'user_id': data['user']['id'],
        'user_name': data['user']['full_name'],
        'testator_name': data['user']['full_name'],
        'instrument_no': c._instrument_no
    }

    # Page 1 (and signature page at the end)
    draw_page_background(c)
    draw_page_border_rules(c)
    draw_page1(c, data, page_data)
    
    c.save()
    output.seek(0)
    return output

def create_mock_data():
    return {
      "user": {
        "id": 15,
        "full_name": "John Q. Public",
        "email": "john.public@example.com",
        "created_at": "2026-05-09T10:00:00Z"
      },
      "assets": [
        { "name": "Facebook", "category": "social", "description": "Primary social media account.", "preferred_action": "memorialize", "created_at": "2026-05-10T11:00:00Z" },
        { "name": "Gmail Account", "category": "email", "description": "Personal email address.", "preferred_action": "download", "created_at": "2026-05-10T11:05:00Z" },
        { "name": "Coinbase Pro", "category": "finance", "description": "Cryptocurrency holdings.", "preferred_action": "transfer", "created_at": "2026-05-11T12:00:00Z" },
        { "name": "iCloud Storage", "category": "storage", "description": "Family photos and documents.", "preferred_action": "pass_executor", "created_at": "2026-05-12T14:30:00Z" },
        { "name": "Old MySpace", "category": "social", "description": "Ancient social media account.", "preferred_action": "delete", "created_at": "2026-05-12T15:00:00Z" }
      ],
      "executors": [
        { "name": "Jane M. Doe", "email": "jane.doe@example.com", "relationship": "Spouse", "status": "verified", "access_granted": True, "created_at": "2026-05-09T10:05:00Z" },
        { "name": "Samuel Smith Jr.", "email": "sam.smith@example.com", "relationship": "Attorney", "status": "pending", "access_granted": False, "created_at": "2026-05-09T10:10:00Z" }
      ],
      "emergency_contacts": []
    }

# ════════════════════════════════════════════════════════════════════════════════
# SCRIPT ENTRY POINT
# ════════════════════════════════════════════════════════════════════════════════

if __name__ == '__main__':
    try:
        if '--test' in sys.argv:
            print("Running in test mode, using mock data...")
            data = create_mock_data()
            pdf_buffer = generate_pdf(data)
            with open('test_will.pdf', 'wb') as f:
                f.write(pdf_buffer.getvalue())
            print("test_will.pdf generated successfully.")
            sys.exit(0)

        # Read JSON from stdin
        data = json.loads(sys.stdin.read())
        
        pdf_buffer = generate_pdf(data)
        
        # Write PDF to stdout in binary mode
        sys.stdout.buffer.write(pdf_buffer.getvalue())

    except json.JSONDecodeError as e:
        sys.stderr.write(f'JSON parsing error: {str(e)}\n')
        sys.exit(1)
    except KeyError as e:
        sys.stderr.write(f'Missing required field in JSON data: {str(e)}\n')
        sys.exit(1)
    except ImportError as e:
        sys.stderr.write(f'Import error (missing dependency): {str(e)}\nInstall reportlab: pip install reportlab\n')
        sys.exit(1)
    except Exception as e:
        import traceback
        sys.stderr.write(f'Unexpected error: {str(e)}\n')
        sys.stderr.write(traceback.format_exc() + '\n')
        sys.exit(1)
